### ISSUE TITLE
hard coded master

### ISSUE THREAD

**Issue by ligi** [sheerun/git-squash#1]
as far as I see this master:

https://github.com/sheerun/git-squash/blob/master/git-squash#L28

should be the branch from the first parameter. So it works if the first parameter is master - but fails in other cases (like mine) with "There are no changes to be squashed"

**Comment by sheerun** [comment]
you are right, thank you for noticing!

**Comment by ligi** [comment]
you are most welcome! Thanks for the tool btw.
btw: it would also be great if I could specify the first commit as parameter. Or is there a way to do this? Something like `--root` for rebase
And just wondering if another use-case could be in scope for this:

squash commits `from`..`to`. Currently only `from` is allowed - but I currently also have a use-case for `to`.
Background: we want to open source something - but only the most recent history (~1year) and need to squash everything before. I can also do it manually now by using your tool and then cherry-picking the following commits - but maybe it would also be a nice addition to this tool?

**Comment by sheerun** [comment]
I could merge feature like this if someone sends a PR (i.e. so one can provide range instead of just branch name, like `git sqush master..HEAD^`), but honestly I don't have time to develop it myself, especially I won't use it :)
